web:
  build: .
  ports:
    - "8080:8080"
  links:
  - db
  volumes:
    - ./build/libs:/app
db:
  image: postgres

#   volumes_from:
#     - dbdata
# dbdata:
#   image: postgres
#   volumes:
#     - /var/lib/postgresql
